// Catalogue des produits TJD.
// Clé = id produit utilisé dans les metadata Stripe et dans les tokens de téléchargement.

const BLOB = "https://pugq0h77i21rhva7.public.blob.vercel-storage.com/tjd";

const PRODUITS = {
  // Fiches compilées – 14,99 €
  "fiche-da-l2-s1":             { nom: "Fiches Droit administratif L2 S1",           prix: 1499, blobs: [`${BLOB}/fiche-da-l2-s1.pdf`] },
  "fiche-da-l2-s2":             { nom: "Fiches Droit administratif L2 S2",           prix: 1499, blobs: [`${BLOB}/fiche-da-l2-s2.pdf`] },
  "fiche-constit-l1-s1":        { nom: "Fiches Droit constitutionnel L1 S1",         prix: 1499, blobs: [`${BLOB}/fiche-constit-l1-s1.pdf`] },
  "fiche-constit-l1-s2":        { nom: "Fiches Droit constitutionnel L1 S2",         prix: 1499, blobs: [`${BLOB}/fiche-constit-l1-s2.pdf`] },
  "fiche-intro-droit-l1":       { nom: "Fiches Introduction au droit L1 S1",         prix: 1499, blobs: [`${BLOB}/fiche-intro-droit-l1.pdf`] },
  "fiche-hist-droit-l1":        { nom: "Fiches Histoire du droit L1 S1",             prix: 1499, blobs: [`${BLOB}/fiche-hist-droit-l1.pdf`] },
  "fiche-hist-institutions-l1": { nom: "Fiches Histoire des institutions L1 S2",     prix: 1499, blobs: [`${BLOB}/fiche-hist-institutions-l1.pdf`] },
  "fiche-personnes-l1":         { nom: "Fiches Droit des personnes L1",              prix: 1499, blobs: [`${BLOB}/fiche-personnes-l1.pdf`] },
  "fiche-famille-l1-s2":        { nom: "Fiches Droit de la famille L1 S2",           prix: 1499, blobs: [`${BLOB}/fiche-famille-l1-s2.pdf`] },
  "fiche-contrats-l2-s1":       { nom: "Fiches Droit des contrats L2 S1",            prix: 1499, blobs: [`${BLOB}/fiche-contrats-l2-s1.pdf`] },
  "fiche-obligations-l2-s2":    { nom: "Fiches Droit des obligations L2 S2",         prix: 1499, blobs: [`${BLOB}/fiche-obligations-l2-s2.pdf`] },
  "fiche-penal-general-l1":     { nom: "Fiches Droit pénal général L1 S2",           prix: 1499, blobs: [`${BLOB}/fiche-penal-general-l1.pdf`] },
  "fiche-penal-l2-s1":          { nom: "Fiches Droit pénal L2 S1",                   prix: 1499, blobs: [`${BLOB}/fiche-penal-l2-s1.pdf`] },
  "fiche-biens-l2":             { nom: "Fiches Droit des biens L2",                  prix: 1499, blobs: [`${BLOB}/fiche-biens-l2.pdf`] },
  "fiche-commercial-l3-s1":     { nom: "Fiches Droit commercial L3 S1",              prix: 1499, blobs: [`${BLOB}/fiche-commercial-l3-s1.pdf`] },
  "fiche-societes-l3-s1":       { nom: "Fiches Droit des sociétés L3 S1",            prix: 1499, blobs: [`${BLOB}/fiche-societes-l3-s1.pdf`] },
  "fiche-contrats-speciaux-l3": { nom: "Fiches Contrats spéciaux L3",                prix: 1499, blobs: [`${BLOB}/fiche-contrats-speciaux-l3.pdf`] },
  "fiche-travail-l3-s1":        { nom: "Fiches Droit du travail L3 S1",              prix: 1499, blobs: [`${BLOB}/fiche-travail-l3-s1.pdf`] },
  "fiche-procedure-penale-l3":  { nom: "Fiches Procédure pénale L3",                 prix: 1499, blobs: [`${BLOB}/fiche-procedure-penale-l3.pdf`] },
  "fiche-relations-internationales-l1": { nom: "Fiches Relations internationales L1", prix: 1499, blobs: [`${BLOB}/fiche-relations-internationales-l1.pdf`] },

  // Majeures préparées – 12,99 €
  "maj-intro-droit-l1":     { nom: "Majeures préparées Introduction au droit L1",    prix: 1299, blobs: [`${BLOB}/maj-intro-droit-l1.pdf`] },
  "maj-personnes-l1":       { nom: "Majeures préparées Droit des personnes L1",      prix: 1299, blobs: [`${BLOB}/maj-personnes-l1.pdf`] },
  "maj-famille-l1-s2":      { nom: "Majeures préparées Droit de la famille L1 S2",   prix: 1299, blobs: [`${BLOB}/maj-famille-l1-s2.pdf`] },
  "maj-da-l2-s1":           { nom: "Majeures préparées Droit administratif L2 S1",   prix: 1299, blobs: [`${BLOB}/maj-da-l2-s1.pdf`] },
  "maj-da-l2-s2":           { nom: "Majeures préparées Droit administratif L2 S2",   prix: 1299, blobs: [`${BLOB}/maj-da-l2-s2.pdf`] },
  "maj-contrats-l2-s1":     { nom: "Majeures préparées Droit des contrats L2 S1",    prix: 1299, blobs: [`${BLOB}/maj-contrats-l2-s1.pdf`] },
  "maj-obligations-l2-s2":  { nom: "Majeures préparées Droit des obligations L2 S2", prix: 1299, blobs: [`${BLOB}/maj-obligations-l2-s2.pdf`] },
  "maj-penal-l2-s1":        { nom: "Majeures préparées Droit pénal L2 S1",           prix: 1299, blobs: [`${BLOB}/maj-penal-l2-s1.pdf`] },
  "maj-penal-l2-s2":        { nom: "Majeures préparées Droit pénal L2 S2",           prix: 1299, blobs: [`${BLOB}/maj-penal-l2-s2.pdf`] },
  "maj-biens-l2":           { nom: "Majeures préparées Droit des biens L2",          prix: 1299, blobs: [`${BLOB}/maj-biens-l2.pdf`] },
  "maj-commercial-l3-s1":   { nom: "Majeures préparées Droit commercial L3 S1",      prix: 1299, blobs: [`${BLOB}/maj-commercial-l3-s1.pdf`] },

  // Cours-fiches – 24,99 €
  "cours-fiche-travail-l3-s1": { nom: "Cours-fiche Droit du travail L3 S1", prix: 2499, blobs: [`${BLOB}/cours-fiche-travail-l3-s1.pdf`] },
  "cours-fiche-societes-l3-s1": { nom: "Cours-fiche Droit des sociétés L3 S1", prix: 2499, blobs: [`${BLOB}/cours-fiche-societes-l3-s1.pdf`] },
  "cours-fiche-commercial-l3-s1": { nom: "Cours-fiche Droit commercial L3 S1", prix: 2499, blobs: [`${BLOB}/cours-fiche-commercial-l3-s1.pdf`] },
  "cours-fiche-procedure-penale-l3": { nom: "Cours-fiche Procédure pénale L3", prix: 2499, blobs: [`${BLOB}/cours-fiche-procedure-penale-l3.pdf`] },
  "cours-fiche-contrats-speciaux-l3": { nom: "Cours-fiche Contrats spéciaux L3", prix: 2499, blobs: [`${BLOB}/cours-fiche-contrats-speciaux-l3.pdf`] },
  "cours-fiche-obligations-l2-s2": { nom: "Cours-fiche Droit des obligations L2 S2", prix: 2499, blobs: [`${BLOB}/cours-fiche-obligations-l2-s2.pdf`] },
  "cours-fiche-da-l2-s2": { nom: "Cours-fiche Droit administratif L2 S2", prix: 2499, blobs: [`${BLOB}/cours-fiche-da-l2-s2.pdf`] },
  "cours-fiche-penal-l2-s1": { nom: "Cours-fiche Droit pénal L2 S1", prix: 2499, blobs: [`${BLOB}/cours-fiche-penal-l2-s1.pdf`] },
  "cours-fiche-contrats-l2-s1": { nom: "Cours-fiche Droit des contrats L2 S1", prix: 2499, blobs: [`${BLOB}/cours-fiche-contrats-l2-s1.pdf`] },
  "cours-fiche-da-l2-s1": { nom: "Cours-fiche Droit administratif L2 S1", prix: 2499, blobs: [`${BLOB}/cours-fiche-da-l2-s1.pdf`] },
  "cours-fiche-biens-l2": { nom: "Cours-fiche Droit des biens L2", prix: 2499, blobs: [`${BLOB}/cours-fiche-biens-l2.pdf`] },
  "cours-fiche-hist-institutions-l1": { nom: "Cours-fiche Histoire des institutions L1 S2", prix: 2499, blobs: [`${BLOB}/cours-fiche-hist-institutions-l1.pdf`] },
  "cours-fiche-penal-general-l1": { nom: "Cours-fiche Droit pénal général L1 S2", prix: 2499, blobs: [`${BLOB}/cours-fiche-penal-general-l1.pdf`] },
  "cours-fiche-famille-l1-s2": { nom: "Cours-fiche Droit de la famille L1 S2", prix: 2499, blobs: [`${BLOB}/cours-fiche-famille-l1-s2.pdf`] },
  "cours-fiche-constit-l1-s2": { nom: "Cours-fiche Droit constitutionnel L1 S2", prix: 2499, blobs: [`${BLOB}/cours-fiche-constit-l1-s2.pdf`] },
  "cours-fiche-intro-droit-l1": { nom: "Cours-fiche Introduction au droit L1 S1", prix: 2499, blobs: [`${BLOB}/cours-fiche-intro-droit-l1.pdf`] },
  "cours-fiche-hist-droit-l1": { nom: "Cours-fiche Histoire du droit L1 S1", prix: 2499, blobs: [`${BLOB}/cours-fiche-hist-droit-l1.pdf`] },
  "cours-fiche-constit-l1-s1": { nom: "Cours-fiche Droit constitutionnel L1 S1", prix: 2499, blobs: [`${BLOB}/cours-fiche-constit-l1-s1.pdf`] },
  "cours-fiche-relations-internationales-l1": { nom: "Cours-fiche Relations internationales L1", prix: 2499, blobs: [`${BLOB}/cours-fiche-relations-internationales-l1.pdf`] },
  "cours-fiche-personnes-l1": { nom: "Cours-fiche Droit des personnes L1", prix: 2499, blobs: [`${BLOB}/cours-fiche-personnes-l1.pdf`] },

  // Fiches d'arrêt – 9,99 €
  "fiche-arret-procedure-penale": { nom: "Fiches d'arrêt Procédure pénale", prix: 999, blobs: [`${BLOB}/fiche-arret-procedure-penale.pdf`] },
  "fiche-arret-penal": { nom: "Fiches d'arrêt Droit pénal", prix: 999, blobs: [`${BLOB}/fiche-arret-penal.pdf`] },
  "fiche-arret-obligations": { nom: "Fiches d'arrêt Droit des obligations", prix: 999, blobs: [`${BLOB}/fiche-arret-obligations.pdf`] },
  "fiche-arret-societes": { nom: "Fiches d'arrêt Droit des sociétés", prix: 999, blobs: [`${BLOB}/fiche-arret-societes.pdf`] },
  "fiche-arret-personnes": { nom: "Fiches d'arrêt Droit des personnes", prix: 999, blobs: [`${BLOB}/fiche-arret-personnes.pdf`] },
  "fiche-arret-contrats": { nom: "Fiches d'arrêt Droit des contrats", prix: 999, blobs: [`${BLOB}/fiche-arret-contrats.pdf`] },
  "fiche-arret-biens": { nom: "Fiches d'arrêt Droit des biens", prix: 999, blobs: [`${BLOB}/fiche-arret-biens.pdf`] },
  "fiche-arret-famille": { nom: "Fiches d'arrêt Droit de la famille", prix: 999, blobs: [`${BLOB}/fiche-arret-famille.pdf`] },
  "fiche-arret-administratif": { nom: "Fiches d'arrêt Droit administratif", prix: 999, blobs: [`${BLOB}/fiche-arret-administratif.pdf`] },
  "fiche-arret-contrats-speciaux-l3": { nom: "Fiches d'arrêt Contrats spéciaux L3", prix: 999, blobs: [`${BLOB}/fiche-arret-contrats-speciaux-l3.pdf`] },

  // Citations – 4,99 €
  "citations-libertes-fondamentales": { nom: "Fiche de citations Libertés fondamentales", prix: 499, blobs: [`${BLOB}/citations-libertes-fondamentales.pdf`] },
  "citations-ue": { nom: "Fiche de citations Droit de l'Union européenne", prix: 499, blobs: [`${BLOB}/citations-ue.pdf`] },
  "citations-rgo-l3": { nom: "Fiche de citations Régime général de l'obligation L3", prix: 499, blobs: [`${BLOB}/citations-rgo-l3.pdf`] },
  "citations-procedure-penale-l3": { nom: "Fiche de citations Procédure pénale L3", prix: 499, blobs: [`${BLOB}/citations-procedure-penale-l3.pdf`] },
  "citations-travail-l3": { nom: "Fiche de citations Droit du travail L3", prix: 499, blobs: [`${BLOB}/citations-travail-l3.pdf`] },
  "citations-societes-l3": { nom: "Fiche de citations Droit des sociétés L3", prix: 499, blobs: [`${BLOB}/citations-societes-l3.pdf`] },
  "citations-penal-l2-s2": { nom: "Fiche de citations Droit pénal L2 S2", prix: 499, blobs: [`${BLOB}/citations-penal-l2-s2.pdf`] },
  "citations-penal-l2-s1": { nom: "Fiche de citations Droit pénal L2 S1", prix: 499, blobs: [`${BLOB}/citations-penal-l2-s1.pdf`] },
  "citations-obligations-l2-s2": { nom: "Fiche de citations Droit des obligations L2 S2", prix: 499, blobs: [`${BLOB}/citations-obligations-l2-s2.pdf`] },
  "citations-obligations-l2-s1": { nom: "Fiche de citations Droit des obligations L2 S1", prix: 499, blobs: [`${BLOB}/citations-obligations-l2-s1.pdf`] },
  "citations-da-l2-s2": { nom: "Fiche de citations Droit administratif L2 S2", prix: 499, blobs: [`${BLOB}/citations-da-l2-s2.pdf`] },
  "citations-da-l2-s1": { nom: "Fiche de citations Droit administratif L2 S1", prix: 499, blobs: [`${BLOB}/citations-da-l2-s1.pdf`] },
  "citations-intro-droit-l1": { nom: "Fiche de citations Introduction au droit L1", prix: 499, blobs: [`${BLOB}/citations-intro-droit-l1.pdf`] },
  "citations-hist-droit-l1": { nom: "Fiche de citations Histoire du droit L1 S1", prix: 499, blobs: [`${BLOB}/citations-hist-droit-l1.pdf`] },
  "citations-personnes-l1": { nom: "Fiche de citations Droit des personnes L1", prix: 499, blobs: [`${BLOB}/citations-personnes-l1.pdf`] },
  "citations-constit-l1-s2": { nom: "Fiche de citations Droit constitutionnel L1 S2", prix: 499, blobs: [`${BLOB}/citations-constit-l1-s2.pdf`] },
  "citations-constit-l1-s1": { nom: "Fiche de citations Droit constitutionnel L1 S1", prix: 499, blobs: [`${BLOB}/citations-constit-l1-s1.pdf`] },

  // Fiches ultra-complètes – 19,99 €
  "fiche-uc-travail-l3-s1": { nom: "Fiches ultra-complètes Droit du travail L3 S1", prix: 1999, blobs: ["https://pub-45b53167be7548aca62650d34a771b47.r2.dev/tjd/fiche-uc-travail-l3-s1.pdf"] },
  "fiche-uc-societes-l3-s1": { nom: "Fiches ultra-complètes Droit des sociétés L3 S1", prix: 1999, blobs: ["https://pub-45b53167be7548aca62650d34a771b47.r2.dev/tjd/fiche-uc-societes-l3-s1.pdf"] },
  "fiche-uc-commercial-l3-s1": { nom: "Fiches ultra-complètes Droit commercial L3 S1", prix: 1999, blobs: [`${BLOB}/fiche-uc-commercial-l3-s1.pdf`] },
  "fiche-uc-procedure-penale-l3": { nom: "Fiches ultra-complètes Procédure pénale L3", prix: 1999, blobs: [`${BLOB}/fiche-uc-procedure-penale-l3.pdf`] },
  "fiche-uc-contrats-speciaux-l3": { nom: "Fiches ultra-complètes Contrats spéciaux L3", prix: 1999, blobs: [`${BLOB}/fiche-uc-contrats-speciaux-l3.pdf`] },
  "fiche-uc-obligations-l2-s2": { nom: "Fiches ultra-complètes Droit des obligations L2 S2", prix: 1999, blobs: [`${BLOB}/fiche-uc-obligations-l2-s2.pdf`] },
  "fiche-uc-da-l2-s2": { nom: "Fiches ultra-complètes Droit administratif L2 S2", prix: 1999, blobs: [`${BLOB}/fiche-uc-da-l2-s2.pdf`] },
  "fiche-uc-penal-l2-s1": { nom: "Fiches ultra-complètes Droit pénal L2 S1", prix: 1999, blobs: [`${BLOB}/fiche-uc-penal-l2-s1.pdf`] },
  "fiche-uc-contrats-l2-s1": { nom: "Fiches ultra-complètes Droit des contrats L2 S1", prix: 1999, blobs: [`${BLOB}/fiche-uc-contrats-l2-s1.pdf`] },
  "fiche-uc-da-l2-s1": { nom: "Fiches ultra-complètes Droit administratif L2 S1", prix: 1999, blobs: [`${BLOB}/fiche-uc-da-l2-s1.pdf`] },
  "fiche-uc-biens-l2": { nom: "Fiches ultra-complètes Droit des biens L2", prix: 1999, blobs: [`${BLOB}/fiche-uc-biens-l2.pdf`] },
  "fiche-uc-hist-institutions-l1": { nom: "Fiches ultra-complètes Histoire des institutions L1 S2", prix: 1999, blobs: [`${BLOB}/fiche-uc-hist-institutions-l1.pdf`] },
  "fiche-uc-famille-l1-s2": { nom: "Fiches ultra-complètes Droit de la famille L1 S2", prix: 1999, blobs: [`${BLOB}/fiche-uc-famille-l1-s2.pdf`] },
  "fiche-uc-penal-general-l1": { nom: "Fiches ultra-complètes Droit pénal général L1 S2", prix: 1999, blobs: [`${BLOB}/fiche-uc-penal-general-l1.pdf`] },
  "fiche-uc-constit-l1-s2": { nom: "Fiches ultra-complètes Droit constitutionnel L1 S2", prix: 1999, blobs: [`${BLOB}/fiche-uc-constit-l1-s2.pdf`] },
  "fiche-uc-intro-droit-l1": { nom: "Fiches ultra-complètes Introduction au droit L1 S1", prix: 1999, blobs: [`${BLOB}/fiche-uc-intro-droit-l1.pdf`] },
  "fiche-uc-hist-droit-l1": { nom: "Fiches ultra-complètes Histoire du droit L1 S1", prix: 1999, blobs: [`${BLOB}/fiche-uc-hist-droit-l1.pdf`] },
  "fiche-uc-constit-l1-s1": { nom: "Fiches ultra-complètes Droit constitutionnel L1 S1", prix: 1999, blobs: [`${BLOB}/fiche-uc-constit-l1-s1.pdf`] },
  "fiche-uc-relations-internationales-l1": { nom: "Fiches ultra-complètes Relations internationales L1", prix: 1999, blobs: [`${BLOB}/fiche-uc-relations-internationales-l1.pdf`] },
  "fiche-uc-personnes-l1": { nom: "Fiches ultra-complètes Droit des personnes L1", prix: 1999, blobs: [`${BLOB}/fiche-uc-personnes-l1.pdf`] },

  // Packs
  "pack-l1": {
    nom: "Pack Fiches L1 intégral (8 matières)",
    prix: 9800,
    blobs: [
      `${BLOB}/fiche-intro-droit-l1.pdf`,
      `${BLOB}/fiche-constit-l1-s1.pdf`,
      `${BLOB}/fiche-constit-l1-s2.pdf`,
      `${BLOB}/fiche-hist-droit-l1.pdf`,
      `${BLOB}/fiche-hist-institutions-l1.pdf`,
      `${BLOB}/fiche-personnes-l1.pdf`,
      `${BLOB}/fiche-famille-l1-s2.pdf`,
      `${BLOB}/fiche-penal-general-l1.pdf`,
    ],
  },
  "pack-l2": {
    nom: "Pack Fiches L2 intégral (6 matières)",
    prix: 6800,
    blobs: [
      `${BLOB}/fiche-da-l2-s1.pdf`,
      `${BLOB}/fiche-da-l2-s2.pdf`,
      `${BLOB}/fiche-contrats-l2-s1.pdf`,
      `${BLOB}/fiche-obligations-l2-s2.pdf`,
      `${BLOB}/fiche-penal-l2-s1.pdf`,
      `${BLOB}/fiche-biens-l2.pdf`,
    ],
  },
  "pack-l3": {
    nom: "Pack Fiches L3 intégral (5 matières)",
    prix: 5800,
    blobs: [
      `${BLOB}/fiche-commercial-l3-s1.pdf`,
      `${BLOB}/fiche-societes-l3-s1.pdf`,
      `${BLOB}/fiche-contrats-speciaux-l3.pdf`,
      `${BLOB}/fiche-travail-l3-s1.pdf`,
      `${BLOB}/fiche-procedure-penale-l3.pdf`,
    ],
  },
  "pack-complet": {
    nom: "Pack Fiches L1+L2+L3 intégral (19 matières)",
    prix: 17900,
    blobs: [
      `${BLOB}/fiche-intro-droit-l1.pdf`,
      `${BLOB}/fiche-constit-l1-s1.pdf`,
      `${BLOB}/fiche-constit-l1-s2.pdf`,
      `${BLOB}/fiche-hist-droit-l1.pdf`,
      `${BLOB}/fiche-hist-institutions-l1.pdf`,
      `${BLOB}/fiche-personnes-l1.pdf`,
      `${BLOB}/fiche-famille-l1-s2.pdf`,
      `${BLOB}/fiche-penal-general-l1.pdf`,
      `${BLOB}/fiche-da-l2-s1.pdf`,
      `${BLOB}/fiche-da-l2-s2.pdf`,
      `${BLOB}/fiche-contrats-l2-s1.pdf`,
      `${BLOB}/fiche-obligations-l2-s2.pdf`,
      `${BLOB}/fiche-penal-l2-s1.pdf`,
      `${BLOB}/fiche-biens-l2.pdf`,
      `${BLOB}/fiche-commercial-l3-s1.pdf`,
      `${BLOB}/fiche-societes-l3-s1.pdf`,
      `${BLOB}/fiche-contrats-speciaux-l3.pdf`,
      `${BLOB}/fiche-travail-l3-s1.pdf`,
      `${BLOB}/fiche-procedure-penale-l3.pdf`,
    ],
  },
};

module.exports = PRODUITS;
